apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-command
  name: edgex-core-command
spec:
  type: NodePort
  ports:
  - name: "48082"
    port: 48082
    targetPort: 48082
    nodePort: 32001 
  selector:
    io.kompose.service: edgex-core-command
status:
  loadBalancer: {}
