apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-data
  name: edgex-core-data
spec:
  type: NodePort
  ports:
  - name: "48080"
    port: 48080
    targetPort: 48080
  - name: "5563"
    port: 5563
    targetPort: 5563
    nodePort: 32009
  selector:
    io.kompose.service: edgex-core-data
status:
  loadBalancer: {}
