apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-export-client
  name:  edgex-export-client
spec:
  type: NodePort
  ports:
  - name: "48071"
    port: 48071
    targetPort: 48071
    nodePort: 32006
  selector:
    io.kompose.service: edgex-export-client
status:
  loadBalancer: {}
